export default{
login: "IgotChuHomie",
id: 37488168,
node_id: "MDQ6VXNlcjM3NDg4MTY4",
avatar_url: "https://avatars.githubusercontent.com/u/37488168?v=4",
gravatar_id: "",
url: "https://api.github.com/users/IgotChuHomie",
html_url: "https://github.com/IgotChuHomie",
followers_url: "https://api.github.com/users/IgotChuHomie/followers",
following_url: "https://api.github.com/users/IgotChuHomie/following{/other_user}",
gists_url: "https://api.github.com/users/IgotChuHomie/gists{/gist_id}",
starred_url: "https://api.github.com/users/IgotChuHomie/starred{/owner}{/repo}",
subscriptions_url: "https://api.github.com/users/IgotChuHomie/subscriptions",
organizations_url: "https://api.github.com/users/IgotChuHomie/orgs",
repos_url: "https://api.github.com/users/IgotChuHomie/repos",
events_url: "https://api.github.com/users/IgotChuHomie/events{/privacy}",
received_events_url: "https://api.github.com/users/IgotChuHomie/received_events",
type: "User",
site_admin: false,
name: "Oussama Abdoune",
company: "I can do push-up on One Arm 3 fingers",
blog: "",
location: "Morocco",
email: null,
hireable: null,
bio: "𝙊𝙥𝙚𝙣 𝙎𝙤𝙪𝙧𝙘𝙚 , 𝙚𝙣𝙩𝙝𝙪𝙨𝙞𝙖𝙨𝙩 , 𝙎𝙥𝙖𝙘𝙚 𝙇𝙤𝙫𝙚𝙧 ,𝙨𝙚𝙢𝙞𝙘𝙤𝙡𝙤𝙣 ❤🐸♬",
twitter_username: "oussamasabir1",
public_repos: 11,
public_gists: 1,
followers: 51,
following: 32,
created_at: "2018-03-17T22:30:00Z",
updated_at: "2022-04-10T01:45:34Z"
}
